networks:
  auth-network:
    driver: bridge
  db-network:
    driver: bridge
  kong-network:
    driver: bridge
  monitoring-network:
    driver: bridge

services:
  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: "no"

  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      - db-network
    environment:
      POSTGRES_DB: petquest-db
      POSTGRES_USER: petquest-db
      POSTGRES_PASSWORD: idpacs1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petquest-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      - db-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@petquest.com
      PGADMIN_DEFAULT_PASSWORD: idpacs1234
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  db-service:
    build: ../Database-Service
    container_name: db-service
    networks:
      - auth-network
      - db-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petquest-db
      SPRING_DATASOURCE_USERNAME: petquest-db
      SPRING_DATASOURCE_PASSWORD: idpacs1234
    depends_on:
      postgres:
        condition: service_healthy

  auth-service:
    build: ../Authentication-Service
    container_name: auth-service
    networks:
      - auth-network
      - kong-network
    environment:
      DB_SERVICE_BASE_URL: http://db-service:8082
      JWT_SECRET: 256-bit-super-secret-key-for-jwt-petquest-idp
      JWT_ACCESS_TOKEN_EXPIRY: 900000
      JWT_REFRESH_TOKEN_EXPIRY: 2592000000
    depends_on:
      - db-service

  kong:
    image: kong:3.6
    container_name: kong
    networks:
      - kong-network
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong.yaml
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yaml:/kong.yaml
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - auth-service
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring-network

volumes:
  postgres-data:
  pgadmin-data:
  portainer-data: