networks:
  auth-network:
    driver: bridge
  db-network:
    driver: bridge

services:

  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      - db-network
    environment:
      POSTGRES_DB: petquest-db
      POSTGRES_USER: petquest-db
      POSTGRES_PASSWORD: idpacs1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petquest-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-service:
    build: ../Database-Service
    container_name: db-service
    networks:
      - auth-network
      - db-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petquest-db
      SPRING_DATASOURCE_USERNAME: petquest-db
      SPRING_DATASOURCE_PASSWORD: idpacs1234
    depends_on:
      postgres:
        condition: service_healthy

  auth-service:
    build: ../Authentication-Service
    container_name: auth-service
    networks:
      - auth-network
    environment:
      DB_SERVICE_BASE_URL: http://db-service:8082
      JWT_SECRET: 256-bit-secret-for-petquest-idp
      JWT_ACCESS_TOKEN_EXPIRY: 900000
      JWT_REFRESH_TOKEN_EXPIRY: 2592000000
    ports:
      - "8081:8081"
    depends_on:
      - db-service

volumes:
  postgres-data: